"""Lead business logic service."""

import logging
from datetime import datetime, timezone

from supabase import AsyncClient

from app.models.lead import Lead
from app.models.schemas import LeadIngest
from app.services.classifier import ClassificationService
from app.services.dedup import DeduplicationService

logger = logging.getLogger(__name__)


class LeadService:
    """Orchestrates lead ingestion, deduplication, and classification."""

    def __init__(
        self,
        db: AsyncClient,
        classifier: ClassificationService,
        dedup_service: DeduplicationService,
    ):
        """Initialize lead service."""
        self.db = db
        self.classifier = classifier
        self.dedup_service = dedup_service

    async def ingest_lead(self, lead_data: LeadIngest, source: str = "api") -> Lead:
        """
        Ingest a new lead with deduplication and classification.

        Process:
        1. Check for duplicates
        2. If duplicate, mark as duplicate and link to original
        3. If new, classify using LLM
        4. Store in database
        """
        logger.info(f"Ingesting lead: {lead_data.email}")

        # Check for duplicates
        duplicate = await self.dedup_service.check_duplicate_email(lead_data.email)

        if duplicate:
            logger.info(f"Duplicate detected: {lead_data.email} -> original: {duplicate.id}")

            # Create duplicate lead record
            new_lead = await self._create_duplicate_lead(lead_data, duplicate.id, source)
            await self.dedup_service.log_duplicate(
                original_lead_id=duplicate.id,
                duplicate_lead_id=new_lead.id,
                match_type="email",
                similarity_score=1.0,
            )
            return new_lead

        # New lead - classify it
        logger.info(f"New lead detected: {lead_data.email}, classifying...")
        new_lead = Lead(
            id="",  # Will be assigned by DB
            email=lead_data.email,
            first_name=lead_data.first_name,
            last_name=lead_data.last_name,
            phone=lead_data.phone,
            company=lead_data.company,
            job_title=lead_data.job_title,
            source=source,
        )

        try:
            # Classify lead using LLM
            classification = await self.classifier.classify_lead(new_lead)

            # Update lead with classification
            new_lead.lead_score = classification["lead_score"]
            new_lead.status = classification["status"]
            new_lead.tags = classification.get("tags", [])
            new_lead.classification_rationale = classification["rationale"]
            new_lead.classified_at = datetime.now(timezone.utc)

            logger.info(
                f"Lead classified: {lead_data.email} -> score={new_lead.lead_score}, status={new_lead.status}"
            )

            # Store in database
            stored_lead = await self._store_lead(new_lead)
            logger.info(f"Lead stored: {stored_lead.id} with score {stored_lead.lead_score}")
            return stored_lead

        except Exception as e:
            logger.error(f"Classification failed for lead {lead_data.email}: {str(e)}")
            # Store lead with error status
            new_lead.status = "processing_error"
            new_lead.classification_rationale = f"Classification error: {str(e)}"
            stored_lead = await self._store_lead(new_lead)
            return stored_lead

    async def _create_duplicate_lead(self, lead_data: LeadIngest, original_id: str, source: str) -> Lead:
        """Create a lead record marked as duplicate."""
        duplicate_lead = Lead(
            id="",
            email=lead_data.email,
            first_name=lead_data.first_name,
            last_name=lead_data.last_name,
            phone=lead_data.phone,
            company=lead_data.company,
            job_title=lead_data.job_title,
            source=source,
            is_duplicate=True,
            original_lead_id=original_id,
        )
        return await self._store_lead(duplicate_lead)

    async def _store_lead(self, lead: Lead) -> Lead:
        """Store lead in database and return with updated ID."""
        lead_dict = lead.to_dict()
        # Remove id for insert (UUID will be generated by database)
        lead_dict.pop("id", None)
        
        # Convert datetime objects to ISO format strings
        if lead_dict.get("received_at"):
            lead_dict["received_at"] = lead_dict["received_at"].isoformat()
        if lead_dict.get("classified_at"):
            lead_dict["classified_at"] = lead_dict["classified_at"].isoformat()
        if lead_dict.get("created_at"):
            lead_dict["created_at"] = lead_dict["created_at"].isoformat()
        if lead_dict.get("updated_at"):
            lead_dict["updated_at"] = lead_dict["updated_at"].isoformat()

        try:
            logger.debug(f"Inserting lead: {lead.email}")
            response = await self.db.table("leads").insert(lead_dict).execute()

            if response.data and len(response.data) > 0:
                stored_data = response.data[0]
                stored_lead = Lead.from_dict(stored_data)

                # Store tags if any
                if lead.tags:
                    await self._store_lead_tags(stored_lead.id, lead.tags)

                logger.info(f"Lead stored successfully: {stored_lead.id}")
                return stored_lead
            else:
                raise Exception("No data returned from insert")

        except Exception as e:
            logger.error(f"Failed to store lead: {str(e)}")
            raise

    async def _store_lead_tags(self, lead_id: str, tags: list[str]) -> None:
        """Store lead tags."""
        if not tags:
            return

        try:
            tag_records = [{"lead_id": lead_id, "tag": tag} for tag in tags]
            logger.debug(f"Storing {len(tags)} tags for lead {lead_id}")
            await self.db.table("lead_tags").insert(tag_records).execute()
            logger.info(f"Stored {len(tags)} tags for lead {lead_id}")
        except Exception as e:
            logger.error(f"Failed to store tags for lead {lead_id}: {str(e)}")
            # Don't fail the entire operation if tags fail

    async def get_lead(self, lead_id: str) -> Lead | None:
        """Retrieve a lead by ID."""
        try:
            logger.debug(f"Retrieving lead: {lead_id}")
            response = await self.db.table("leads").select("*").eq("id", lead_id).execute()

            if response.data and len(response.data) > 0:
                lead_data = response.data[0]
                lead = Lead.from_dict(lead_data)

                # Load tags
                tags_response = await self.db.table("lead_tags").select("tag").eq("lead_id", lead_id).execute()
                if tags_response.data:
                    lead.tags = [t["tag"] for t in tags_response.data]

                logger.info(f"Retrieved lead: {lead_id}")
                return lead
            else:
                logger.warning(f"Lead not found: {lead_id}")
                return None
        except Exception as e:
            logger.error(f"Failed to retrieve lead {lead_id}: {str(e)}")
            raise

